# Generated by Django 4.0.1 on 2022-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='resposta',
        ),
    ]
