# Generated by Django 4.0.1 on 2022-04-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_pessoas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
