# Generated by Django 4.0.1 on 2022-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='name',
            field=models.CharField(default=50, max_length=50),
        ),
    ]
