# Generated by Django 4.0.1 on 2022-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_link_data_criacao_alter_comentario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='data_criacao',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
