# Generated by Django 4.0.1 on 2022-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_alter_link_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='click',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
