# Generated by Django 4.0.1 on 2022-05-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_link_click_alter_link_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='click',
        ),
    ]
