# Generated by Django 4.0.1 on 2022-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_remove_link_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='arquivo',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='link',
            name='arquivo',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
